LogFormat "[NOLA_HTTP] ts=%{%Y-%m-%dT%H:%M:%S%z}t remote_ip=%a request=\"%r\" status=%>s bytes=%B duration_us=%D referer=\"%{Referer}i\" user_agent=\"%{User-Agent}i\" request_id=\"%{X-Request-ID}i\"" nola_request

CustomLog /proc/self/fd/1 nola_request
